clear all, close all

%% Get Datas from Pre-Simulation
load('../datas_from_pre_simulation')
clear l0_interface_input_noise
clear l1_neuron_activation_function_dnd
clear l1_neuron_activation_function_res
clear l1_neuron_activation_function_x
clear l1_neuron_activation_function_y
clear l2_neuron_activation_function_e_bar_dnd
clear l2_neuron_activation_function_e_bar_res
clear l2_neuron_activation_function_e_bar_x
clear l2_neuron_activation_function_e_bar_y
clear l2_neuron_activation_function_h_bar_dnd
clear l2_neuron_activation_function_h_bar_res
clear l2_neuron_activation_function_h_bar_x
clear l2_neuron_activation_function_h_bar_y
clear l2_neuron_activation_function_v_bar_dnd
clear l2_neuron_activation_function_v_bar_res
clear l2_neuron_activation_function_v_bar_x
clear l2_neuron_activation_function_v_bar_y
load('../hw_funtions')
